/usr/local/bin/gpio export 7 out
/usr/local/bin/gpio write 7 0
/usr/local/bin/gpio export 15 out
/usr/local/bin/gpio write 15 0
/usr/local/bin/gpio export 16 out
/usr/local/bin/gpio write 16 0
/usr/local/bin/gpio export 0 out
/usr/local/bin/gpio write 0 0
/usr/local/bin/gpio export 1 out
/usr/local/bin/gpio write 1 0
/usr/local/bin/gpio export 2 out
/usr/local/bin/gpio write 2 0
/usr/local/bin/gpio export 3 out
/usr/local/bin/gpio write 3 0
/usr/local/bin/gpio export 4 out
/usr/local/bin/gpio write 4 0
/usr/local/bin/gpio export 5 out
/usr/local/bin/gpio write 5 0
/usr/local/bin/gpio export 12 out
/usr/local/bin/gpio write 12 0
/usr/local/bin/gpio export 13 out
/usr/local/bin/gpio write 13 0
/usr/local/bin/gpio export 6 out
/usr/local/bin/gpio write 6 0
/usr/local/bin/gpio export 14 out
/usr/local/bin/gpio write 14 0
/usr/local/bin/gpio export 10 out
/usr/local/bin/gpio write 10 0
/usr/local/bin/gpio export 11 out
/usr/local/bin/gpio write 11 0
/usr/local/bin/gpio export 21 out
/usr/local/bin/gpio write 21 0
/usr/local/bin/gpio export 26 out
/usr/local/bin/gpio write 26 0
/usr/local/bin/gpio export 23 out
/usr/local/bin/gpio write 23 0
/usr/local/bin/gpio export 24 out
/usr/local/bin/gpio write 24 0
/usr/local/bin/gpio export 27 out
/usr/local/bin/gpio write 27 0
/usr/local/bin/gpio export 25 out
/usr/local/bin/gpio write 25 0
/usr/local/bin/gpio export 28 out
/usr/local/bin/gpio write 28 0
/usr/local/bin/gpio export 29 out
/usr/local/bin/gpio write 29 0
